### ISSUE TITLE
Canny io - Feedback flow, Roadmap, Updates, Community & My activity

### ISSUE THREAD

**Issue by Monika-APM** [sparrowapp-dev/sparrow-app#1449]
This feature is created to track stories of Canny io - Roadmap, Updates, Community & My activity.  Below are the tasks created:

- [x] https://github.com/sparrowapp-dev/sparrow-app/issues/1447
- [x] https://github.com/sparrowapp-dev/sparrow-app/issues/1448
- [x] https://github.com/sparrowapp-dev/sparrow-app/issues/1450
- [x] https://github.com/sparrowapp-dev/sparrow-app/issues/1451
- [x] https://github.com/sparrowapp-dev/sparrow-app/issues/1452
- [x] https://github.com/sparrowapp-dev/sparrow-app/issues/1453
- [x] https://github.com/sparrowapp-dev/sparrow-app/issues/1430
- [x] https://github.com/sparrowapp-dev/sparrow-app/issues/1439
